import { Poppins, Source_Sans_Pro as SourceSansPro } from 'next/font/google';

import Footer from '@/components/Footer/Footer';
import Header from '@/components/Header/Header';

import '../styles/globals.scss';
import styles from './layout.module.scss';

const { WORDPRESS_API_URL } = process.env;

export const sourceSansPro = SourceSansPro({
  display: 'swap',
  subsets: ['latin'],
  variable: '--source-sans-pro-font',
  weight: ['400'],
});

export const poppins = Poppins({
  display: 'swap',
  subsets: ['latin'],
  variable: '--poppins-font',
  weight: ['700', '800', '900'],
});

export const metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

const getCategories = async () => {
  const URL = `${WORDPRESS_API_URL}/categories?acf_format=standard`;
  const response = await fetch(URL, { next: { revalidate: 60 * 60 * 24 } });
  return response.json();
};

const RootLayout = async ({ children }) => {
  const categories = await getCategories();

  return (
    <html lang="en" className="theme-light">
      <body className={`${poppins.variable} ${sourceSansPro.variable}`}>
        <Header categories={categories} />
        <div className={styles.children}>{children}</div>
        <Footer />
      </body>
    </html>
  );
};

export default RootLayout;
