import { Roboto } from 'next/font/google';

import Footer from '@/components/Footer/Footer';
import Header from '@/components/Header/Header';

import '../styles/globals.scss';
import styles from './layout.module.scss';

const roboto = Roboto({
  display: 'swap',
  subsets: ['latin'],
  weight: ['300', '400', '500', '700'],
});

export const metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

const RootLayout = ({ children }) => (
  <html lang="en" className="theme-light">
    <body className={roboto.className}>
      <Header />
      <div className={styles.children}>{children}</div>
      <Footer />
    </body>
  </html>
);

export default RootLayout;
